<?php

include_once 'svv_tools.features.inc';

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * @param type $settings
 * @param type $context
 */
function svv_tools_wysiwyg_editor_settings_alter(&$settings, $context) {
  // We only add the settings to ckeditor wysiwyg profiles.
  if ($context['profile']->editor == 'ckeditor') {
    $format = $context['profile']->format;
    $path = drupal_get_path('module', 'svv_tools') . '/js';
    $settings['stylesSet'] = "svv:/$path/ckeditor_styles.js";
  }
}
