#!/usr/bin/env bash

git stash
git checkout master
git pull origin master

fin drush up -y;

git add misc/*
git add modules/*
git add themes/*
git add includes/*
git commit -m "updating core & contrib packages"
git push origin master

git stash pop